//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEPI.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaborador
    {
        public int RE { get; set; }
        public string Nome { get; set; }
        public string Funcao { get; set; }
    }
}
