//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEPI.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPI
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public Nullable<int> CA { get; set; }
        public System.DateTime DataEntrada { get; set; }
        public int Quantidade { get; set; }
    }
}
